name: ci

on:
  [pull_request, push]:
    branches: [main]
    

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Check out code
        uses: actions/checkout@v3

      # - name: Force Failure
      #   run: go test -cover ./...
      #
        #
  style:
    name: Style
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/go
      GOBIN: ${{ github.workspace }}/go/bin
      PATH: ${{ github.workspace }}/go/bin:${{ env.PATH }}

    steps:
      - name: Format check
        run: test -z $(go fmt ./...)
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Lint check
        run: staticcheck ./...


